levelfive/levelfive/urls.py
from django.contrib import admin
from django.urls import path,include
from levfiv import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('levfiv/',include('levfiv.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

levelfive/levfiv/urls.py
from django.urls import path
from levfiv import views

app_name = 'levfiv'

urlpatterns=[
	path('register/',views.register,name='register'),
	path('user_login/',views.user_login,name='user_login'),
]

levelfive/levfiv/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):

	user=models.OneToOneField(User,on_delete=models.CASCADE)

	portfolio_site = models.URLField(blank=True)

	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


	def __str__(self):
		return self.user.username

levelfive/levfiv/forms.py
from django import forms
from django.contrib.auth.models import User
from levfiv.models import UserProfileInfo


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model=User
		fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site','profile_pic')

levelfive/levfiv/views.py
from django.shortcuts import render
from levfiv.forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def index(request):
	return render(request,'levfiv/index.html')


@login_required
def special(request):
	return HttpResponse(request,"you Are loged in ")


@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

def register(request):
	registered = False

	if request.method == "POST":
		user_form = UserForm(data=request.POST)

		profile_form = UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user=user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']

			profile.save()

			registered = True
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()

	return render(request,'levfiv/registration.html',
								{'user_form':user_form,
								 'profile_form':profile_form,
								 'registered':registered})


def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))

			else:
				return HttpResponse("Account Not active")
		else:
			print("Someone tried to login and failed")
			print("username: {} and password: {}".format(username,password))
			return HttpResponse("inavlid login details supplied!")
	else:
		return render(request,'levfiv/login.html',{})

levelfive/templates/levfiv/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNavDropdown">
		    <ul class="navbar-nav">
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'levfiv:register' %}">Register</a>
		      </li>
		      {% if user.is_authenticated %}
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
		      </li>
		      {% else %}
		      	<li class="nav-item">
		        <a class="nav-link" href="{% url 'levfiv:user_login' %}">Login</a>
		      </li>
		      {% endif %}
    </ul>
  </div>
</nav>

	
	<div class="container">
	{% block body_block %}
	{% endblock %}

	</div>
</body>
</html>

levelfive/templates/levfiv/index.html
{% extends "levfiv/base.html" %}
{% block body_block %}

<div class="jumbotron">
	<h1>Django Level Five</h1>
</div>

{% endblock %}

levelfive/templates/levfiv/login.html
{% extends 'levfiv/base.html' %}
{% block body_block %}

<div class="jumbotron">
	<h1>Please Login</h1>
	<form action="{% url 'levfiv:user_login' %}" method="post">
		{% csrf_token %}
		<label for="username" >Username:</label>
		<input type="test" name="username" placeholder="Enter Username">
		<label for="password" >Password:</label>
		<input type="password" name="password">
		<input type="submit" name="" value="Login">
	</form>
</div>

{% endblock %}

levelfive/templates/levfiv/registration.html
{% extends 'levfiv/base.html' %}
{% load static %}


{% block body_block %}

<div class="jumbotron">
	
	{% if registered %}
		<h1>Thank you for register</h1>
	{% else %}
		<h1>Register Here</h1>
		<h3>Fill Out The Form:</h3>

	<form method='post' enctype="multipart/form-data">
		{% csrf_token %}
		{{ user_form.as_p }}
		{{ profile_form.as_p }}
		<input type="submit" name="" value=Register>
	</form>
	{% endif %}

</div>

{% endblock %}